// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: auth_service/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "schedule_gateway/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginWithGoogleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GoogleAccessToken string                 `protobuf:"bytes,1,opt,name=google_access_token,json=googleAccessToken,proto3" json:"google_access_token"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LoginWithGoogleRequest) Reset() {
	*x = LoginWithGoogleRequest{}
	mi := &file_auth_service_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithGoogleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithGoogleRequest) ProtoMessage() {}

func (x *LoginWithGoogleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithGoogleRequest.ProtoReflect.Descriptor instead.
func (*LoginWithGoogleRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginWithGoogleRequest) GetGoogleAccessToken() string {
	if x != nil {
		return x.GoogleAccessToken
	}
	return ""
}

type LoginWithGoogleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *common.Error          `protobuf:"bytes,1,opt,name=error,proto3" json:"error"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithGoogleResponse) Reset() {
	*x = LoginWithGoogleResponse{}
	mi := &file_auth_service_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithGoogleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithGoogleResponse) ProtoMessage() {}

func (x *LoginWithGoogleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithGoogleResponse.ProtoReflect.Descriptor instead.
func (*LoginWithGoogleResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginWithGoogleResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *LoginWithGoogleResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginWithGoogleResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ResourceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource"`
	Actions       []*Action              `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceItem) Reset() {
	*x = ResourceItem{}
	mi := &file_auth_service_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceItem) ProtoMessage() {}

func (x *ResourceItem) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceItem.ProtoReflect.Descriptor instead.
func (*ResourceItem) Descriptor() ([]byte, []int) {
	return file_auth_service_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceItem) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ResourceItem) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type SaveRouteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ResourceItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRouteResourceRequest) Reset() {
	*x = SaveRouteResourceRequest{}
	mi := &file_auth_service_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRouteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRouteResourceRequest) ProtoMessage() {}

func (x *SaveRouteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRouteResourceRequest.ProtoReflect.Descriptor instead.
func (*SaveRouteResourceRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SaveRouteResourceRequest) GetItems() []*ResourceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SaveRouteResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRouteResourceResponse) Reset() {
	*x = SaveRouteResourceResponse{}
	mi := &file_auth_service_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRouteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRouteResourceResponse) ProtoMessage() {}

func (x *SaveRouteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRouteResourceResponse.ProtoReflect.Descriptor instead.
func (*SaveRouteResourceResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SaveRouteResourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveRouteResourceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_service_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *common.Error          `protobuf:"bytes,1,opt,name=error,proto3" json:"error"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_service_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_service_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_auth_proto_rawDescGZIP(), []int{7}
}

func (x *LogoutRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_auth_service_auth_proto protoreflect.FileDescriptor

const file_auth_service_auth_proto_rawDesc = "" +
	"\n" +
	"\x17auth_service/auth.proto\x12\x04auth\x1a\x1eauth_service/common.auth.proto\x1a\x13common/common.proto\x1a\x12common/error.proto\"H\n" +
	"\x16LoginWithGoogleRequest\x12.\n" +
	"\x13google_access_token\x18\x01 \x01(\tR\x11googleAccessToken\"\x86\x01\n" +
	"\x17LoginWithGoogleResponse\x12#\n" +
	"\x05error\x18\x01 \x01(\v2\r.common.ErrorR\x05error\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\"b\n" +
	"\fResourceItem\x12*\n" +
	"\bresource\x18\x01 \x01(\v2\x0e.auth.ResourceR\bresource\x12&\n" +
	"\aactions\x18\x02 \x03(\v2\f.auth.ActionR\aactions\"D\n" +
	"\x18SaveRouteResourceRequest\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.auth.ResourceItemR\x05items\"O\n" +
	"\x19SaveRouteResourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x13RefreshTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"\x83\x01\n" +
	"\x14RefreshTokenResponse\x12#\n" +
	"\x05error\x18\x01 \x01(\v2\r.common.ErrorR\x05error\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\"W\n" +
	"\rLogoutRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken2\xb0\x02\n" +
	"\vAuthService\x12N\n" +
	"\x0fLoginWithGoogle\x12\x1c.auth.LoginWithGoogleRequest\x1a\x1d.auth.LoginWithGoogleResponse\x12E\n" +
	"\fRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x1a.auth.RefreshTokenResponse\x124\n" +
	"\x06Logout\x12\x13.auth.LogoutRequest\x1a\x15.common.EmptyResponse\x12T\n" +
	"\x11SaveRouteResource\x12\x1e.auth.SaveRouteResourceRequest\x1a\x1f.auth.SaveRouteResourceResponseB\fZ\n" +
	"proto/authb\x06proto3"

var (
	file_auth_service_auth_proto_rawDescOnce sync.Once
	file_auth_service_auth_proto_rawDescData []byte
)

func file_auth_service_auth_proto_rawDescGZIP() []byte {
	file_auth_service_auth_proto_rawDescOnce.Do(func() {
		file_auth_service_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_service_auth_proto_rawDesc), len(file_auth_service_auth_proto_rawDesc)))
	})
	return file_auth_service_auth_proto_rawDescData
}

var file_auth_service_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_service_auth_proto_goTypes = []any{
	(*LoginWithGoogleRequest)(nil),    // 0: auth.LoginWithGoogleRequest
	(*LoginWithGoogleResponse)(nil),   // 1: auth.LoginWithGoogleResponse
	(*ResourceItem)(nil),              // 2: auth.ResourceItem
	(*SaveRouteResourceRequest)(nil),  // 3: auth.SaveRouteResourceRequest
	(*SaveRouteResourceResponse)(nil), // 4: auth.SaveRouteResourceResponse
	(*RefreshTokenRequest)(nil),       // 5: auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),      // 6: auth.RefreshTokenResponse
	(*LogoutRequest)(nil),             // 7: auth.LogoutRequest
	(*common.Error)(nil),              // 8: common.Error
	(*Resource)(nil),                  // 9: auth.Resource
	(*Action)(nil),                    // 10: auth.Action
	(*common.EmptyResponse)(nil),      // 11: common.EmptyResponse
}
var file_auth_service_auth_proto_depIdxs = []int32{
	8,  // 0: auth.LoginWithGoogleResponse.error:type_name -> common.Error
	9,  // 1: auth.ResourceItem.resource:type_name -> auth.Resource
	10, // 2: auth.ResourceItem.actions:type_name -> auth.Action
	2,  // 3: auth.SaveRouteResourceRequest.items:type_name -> auth.ResourceItem
	8,  // 4: auth.RefreshTokenResponse.error:type_name -> common.Error
	0,  // 5: auth.AuthService.LoginWithGoogle:input_type -> auth.LoginWithGoogleRequest
	5,  // 6: auth.AuthService.RefreshToken:input_type -> auth.RefreshTokenRequest
	7,  // 7: auth.AuthService.Logout:input_type -> auth.LogoutRequest
	3,  // 8: auth.AuthService.SaveRouteResource:input_type -> auth.SaveRouteResourceRequest
	1,  // 9: auth.AuthService.LoginWithGoogle:output_type -> auth.LoginWithGoogleResponse
	6,  // 10: auth.AuthService.RefreshToken:output_type -> auth.RefreshTokenResponse
	11, // 11: auth.AuthService.Logout:output_type -> common.EmptyResponse
	4,  // 12: auth.AuthService.SaveRouteResource:output_type -> auth.SaveRouteResourceResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_auth_service_auth_proto_init() }
func file_auth_service_auth_proto_init() {
	if File_auth_service_auth_proto != nil {
		return
	}
	file_auth_service_common_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_service_auth_proto_rawDesc), len(file_auth_service_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_service_auth_proto_goTypes,
		DependencyIndexes: file_auth_service_auth_proto_depIdxs,
		MessageInfos:      file_auth_service_auth_proto_msgTypes,
	}.Build()
	File_auth_service_auth_proto = out.File
	file_auth_service_auth_proto_goTypes = nil
	file_auth_service_auth_proto_depIdxs = nil
}
