// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: auth_service/common.auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_auth_service_common_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_common_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_auth_service_common_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_auth_service_common_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_common_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_auth_service_common_auth_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PermissionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermId        string                 `protobuf:"bytes,1,opt,name=perm_id,json=permId,proto3" json:"perm_id"`
	PermName      string                 `protobuf:"bytes,2,opt,name=perm_name,json=permName,proto3" json:"perm_name"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	IsRoot        bool                   `protobuf:"varint,4,opt,name=is_root,json=isRoot,proto3" json:"is_root"`
	Resource      *Resource              `protobuf:"bytes,5,opt,name=resource,proto3,oneof" json:"resource"`
	Actions       []*Action              `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions"`
	UpdatedAt     *int64                 `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at"`
	CreatedAt     *int64                 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionItem) Reset() {
	*x = PermissionItem{}
	mi := &file_auth_service_common_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionItem) ProtoMessage() {}

func (x *PermissionItem) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_common_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionItem.ProtoReflect.Descriptor instead.
func (*PermissionItem) Descriptor() ([]byte, []int) {
	return file_auth_service_common_auth_proto_rawDescGZIP(), []int{2}
}

func (x *PermissionItem) GetPermId() string {
	if x != nil {
		return x.PermId
	}
	return ""
}

func (x *PermissionItem) GetPermName() string {
	if x != nil {
		return x.PermName
	}
	return ""
}

func (x *PermissionItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PermissionItem) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

func (x *PermissionItem) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *PermissionItem) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *PermissionItem) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *PermissionItem) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

type RoleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	IsRoot        bool                   `protobuf:"varint,4,opt,name=is_root,json=isRoot,proto3" json:"is_root"`
	Permissions   []*PermissionItem      `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions"`
	UpdatedAt     *int64                 `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at"`
	CreatedAt     *int64                 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at"`
	TotalUsers    int32                  `protobuf:"varint,8,opt,name=total_users,json=totalUsers,proto3" json:"total_users"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleItem) Reset() {
	*x = RoleItem{}
	mi := &file_auth_service_common_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleItem) ProtoMessage() {}

func (x *RoleItem) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_common_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleItem.ProtoReflect.Descriptor instead.
func (*RoleItem) Descriptor() ([]byte, []int) {
	return file_auth_service_common_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RoleItem) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RoleItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoleItem) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

func (x *RoleItem) GetPermissions() []*PermissionItem {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *RoleItem) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *RoleItem) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *RoleItem) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *RoleItem) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UserItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email"`
	PasswordHash   string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash"`
	LockEnd        int64                  `protobuf:"varint,4,opt,name=lock_end,json=lockEnd,proto3" json:"lock_end"`
	LockReason     string                 `protobuf:"bytes,5,opt,name=lock_reason,json=lockReason,proto3" json:"lock_reason"`
	LastLoginAt    int64                  `protobuf:"varint,6,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at"`
	FailedAttempts int32                  `protobuf:"varint,7,opt,name=failed_attempts,json=failedAttempts,proto3" json:"failed_attempts"`
	CreatedAt      int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt      int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserItem) Reset() {
	*x = UserItem{}
	mi := &file_auth_service_common_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserItem) ProtoMessage() {}

func (x *UserItem) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_common_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserItem.ProtoReflect.Descriptor instead.
func (*UserItem) Descriptor() ([]byte, []int) {
	return file_auth_service_common_auth_proto_rawDescGZIP(), []int{4}
}

func (x *UserItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserItem) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserItem) GetLockEnd() int64 {
	if x != nil {
		return x.LockEnd
	}
	return 0
}

func (x *UserItem) GetLockReason() string {
	if x != nil {
		return x.LockReason
	}
	return ""
}

func (x *UserItem) GetLastLoginAt() int64 {
	if x != nil {
		return x.LastLoginAt
	}
	return 0
}

func (x *UserItem) GetFailedAttempts() int32 {
	if x != nil {
		return x.FailedAttempts
	}
	return 0
}

func (x *UserItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_auth_service_common_auth_proto protoreflect.FileDescriptor

const file_auth_service_common_auth_proto_rawDesc = "" +
	"\n" +
	"\x1eauth_service/common.auth.proto\x12\x04auth\".\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\",\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xcd\x02\n" +
	"\x0ePermissionItem\x12\x17\n" +
	"\aperm_id\x18\x01 \x01(\tR\x06permId\x12\x1b\n" +
	"\tperm_name\x18\x02 \x01(\tR\bpermName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\ais_root\x18\x04 \x01(\bR\x06isRoot\x12/\n" +
	"\bresource\x18\x05 \x01(\v2\x0e.auth.ResourceH\x00R\bresource\x88\x01\x01\x12&\n" +
	"\aactions\x18\x06 \x03(\v2\f.auth.ActionR\aactions\x12\"\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03H\x01R\tupdatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\b \x01(\x03H\x02R\tcreatedAt\x88\x01\x01B\v\n" +
	"\t_resourceB\r\n" +
	"\v_updated_atB\r\n" +
	"\v_created_at\"\xce\x02\n" +
	"\bRoleItem\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\ais_root\x18\x04 \x01(\bR\x06isRoot\x126\n" +
	"\vpermissions\x18\x05 \x03(\v2\x14.auth.PermissionItemR\vpermissions\x12\"\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03H\x00R\tupdatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\a \x01(\x03H\x01R\tcreatedAt\x88\x01\x01\x12\x1f\n" +
	"\vtotal_users\x18\b \x01(\x05R\n" +
	"totalUsers\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActiveB\r\n" +
	"\v_updated_atB\r\n" +
	"\v_created_at\"\xa5\x02\n" +
	"\bUserItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x19\n" +
	"\block_end\x18\x04 \x01(\x03R\alockEnd\x12\x1f\n" +
	"\vlock_reason\x18\x05 \x01(\tR\n" +
	"lockReason\x12\"\n" +
	"\rlast_login_at\x18\x06 \x01(\x03R\vlastLoginAt\x12'\n" +
	"\x0ffailed_attempts\x18\a \x01(\x05R\x0efailedAttempts\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAtB\fZ\n" +
	"proto/authb\x06proto3"

var (
	file_auth_service_common_auth_proto_rawDescOnce sync.Once
	file_auth_service_common_auth_proto_rawDescData []byte
)

func file_auth_service_common_auth_proto_rawDescGZIP() []byte {
	file_auth_service_common_auth_proto_rawDescOnce.Do(func() {
		file_auth_service_common_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_service_common_auth_proto_rawDesc), len(file_auth_service_common_auth_proto_rawDesc)))
	})
	return file_auth_service_common_auth_proto_rawDescData
}

var file_auth_service_common_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_auth_service_common_auth_proto_goTypes = []any{
	(*Resource)(nil),       // 0: auth.Resource
	(*Action)(nil),         // 1: auth.Action
	(*PermissionItem)(nil), // 2: auth.PermissionItem
	(*RoleItem)(nil),       // 3: auth.RoleItem
	(*UserItem)(nil),       // 4: auth.UserItem
}
var file_auth_service_common_auth_proto_depIdxs = []int32{
	0, // 0: auth.PermissionItem.resource:type_name -> auth.Resource
	1, // 1: auth.PermissionItem.actions:type_name -> auth.Action
	2, // 2: auth.RoleItem.permissions:type_name -> auth.PermissionItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_auth_service_common_auth_proto_init() }
func file_auth_service_common_auth_proto_init() {
	if File_auth_service_common_auth_proto != nil {
		return
	}
	file_auth_service_common_auth_proto_msgTypes[2].OneofWrappers = []any{}
	file_auth_service_common_auth_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_service_common_auth_proto_rawDesc), len(file_auth_service_common_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_service_common_auth_proto_goTypes,
		DependencyIndexes: file_auth_service_common_auth_proto_depIdxs,
		MessageInfos:      file_auth_service_common_auth_proto_msgTypes,
	}.Build()
	File_auth_service_common_auth_proto = out.File
	file_auth_service_common_auth_proto_goTypes = nil
	file_auth_service_common_auth_proto_depIdxs = nil
}
