// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: auth_service/permission.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "schedule_gateway/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourcesRequest) Reset() {
	*x = GetResourcesRequest{}
	mi := &file_auth_service_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourcesRequest) ProtoMessage() {}

func (x *GetResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourcesRequest.ProtoReflect.Descriptor instead.
func (*GetResourcesRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_proto_rawDescGZIP(), []int{0}
}

type GetResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources"`
	Error         *common.Error          `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourcesResponse) Reset() {
	*x = GetResourcesResponse{}
	mi := &file_auth_service_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourcesResponse) ProtoMessage() {}

func (x *GetResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourcesResponse.ProtoReflect.Descriptor instead.
func (*GetResourcesResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_proto_rawDescGZIP(), []int{1}
}

func (x *GetResourcesResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *GetResourcesResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionsRequest) Reset() {
	*x = GetActionsRequest{}
	mi := &file_auth_service_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionsRequest) ProtoMessage() {}

func (x *GetActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionsRequest.ProtoReflect.Descriptor instead.
func (*GetActionsRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_proto_rawDescGZIP(), []int{2}
}

func (x *GetActionsRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type GetActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions"`
	Error         *common.Error          `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionsResponse) Reset() {
	*x = GetActionsResponse{}
	mi := &file_auth_service_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionsResponse) ProtoMessage() {}

func (x *GetActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionsResponse.ProtoReflect.Descriptor instead.
func (*GetActionsResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_proto_rawDescGZIP(), []int{3}
}

func (x *GetActionsResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *GetActionsResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search"`
	PageQuery     *common.PageQuery      `protobuf:"bytes,2,opt,name=page_query,json=pageQuery,proto3" json:"page_query"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionsRequest) Reset() {
	*x = GetPermissionsRequest{}
	mi := &file_auth_service_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsRequest) ProtoMessage() {}

func (x *GetPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_proto_rawDescGZIP(), []int{4}
}

func (x *GetPermissionsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetPermissionsRequest) GetPageQuery() *common.PageQuery {
	if x != nil {
		return x.PageQuery
	}
	return nil
}

func (x *GetPermissionsRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type GetPermissionsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Permissions       []*PermissionItem      `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions"`
	PageInfo          *common.PageInfo       `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info"`
	TotalPermissions  int32                  `protobuf:"varint,3,opt,name=total_permissions,json=totalPermissions,proto3" json:"total_permissions"`
	Root              int32                  `protobuf:"varint,4,opt,name=root,proto3" json:"root"`
	NonRoot           int32                  `protobuf:"varint,5,opt,name=non_root,json=nonRoot,proto3" json:"non_root"`
	RootPercentage    float64                `protobuf:"fixed64,6,opt,name=root_percentage,json=rootPercentage,proto3" json:"root_percentage"`
	NonRootPercentage float64                `protobuf:"fixed64,7,opt,name=non_root_percentage,json=nonRootPercentage,proto3" json:"non_root_percentage"`
	Error             *common.Error          `protobuf:"bytes,8,opt,name=error,proto3,oneof" json:"error"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetPermissionsResponse) Reset() {
	*x = GetPermissionsResponse{}
	mi := &file_auth_service_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsResponse) ProtoMessage() {}

func (x *GetPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_proto_rawDescGZIP(), []int{5}
}

func (x *GetPermissionsResponse) GetPermissions() []*PermissionItem {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetPermissionsResponse) GetPageInfo() *common.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *GetPermissionsResponse) GetTotalPermissions() int32 {
	if x != nil {
		return x.TotalPermissions
	}
	return 0
}

func (x *GetPermissionsResponse) GetRoot() int32 {
	if x != nil {
		return x.Root
	}
	return 0
}

func (x *GetPermissionsResponse) GetNonRoot() int32 {
	if x != nil {
		return x.NonRoot
	}
	return 0
}

func (x *GetPermissionsResponse) GetRootPercentage() float64 {
	if x != nil {
		return x.RootPercentage
	}
	return 0
}

func (x *GetPermissionsResponse) GetNonRootPercentage() float64 {
	if x != nil {
		return x.NonRootPercentage
	}
	return 0
}

func (x *GetPermissionsResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionId  string                 `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionRequest) Reset() {
	*x = GetPermissionRequest{}
	mi := &file_auth_service_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionRequest) ProtoMessage() {}

func (x *GetPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_proto_rawDescGZIP(), []int{6}
}

func (x *GetPermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

type GetPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *PermissionItem        `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission"`
	Error         *common.Error          `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionResponse) Reset() {
	*x = GetPermissionResponse{}
	mi := &file_auth_service_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionResponse) ProtoMessage() {}

func (x *GetPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_proto_rawDescGZIP(), []int{7}
}

func (x *GetPermissionResponse) GetPermission() *PermissionItem {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *GetPermissionResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpsertPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionId  *string                `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3,oneof" json:"permission_id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	ResourceId    string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id"`
	ActionsIds    []string               `protobuf:"bytes,5,rep,name=actions_ids,json=actionsIds,proto3" json:"actions_ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPermissionRequest) Reset() {
	*x = UpsertPermissionRequest{}
	mi := &file_auth_service_permission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPermissionRequest) ProtoMessage() {}

func (x *UpsertPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPermissionRequest.ProtoReflect.Descriptor instead.
func (*UpsertPermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertPermissionRequest) GetPermissionId() string {
	if x != nil && x.PermissionId != nil {
		return *x.PermissionId
	}
	return ""
}

func (x *UpsertPermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertPermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpsertPermissionRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *UpsertPermissionRequest) GetActionsIds() []string {
	if x != nil {
		return x.ActionsIds
	}
	return nil
}

type UpsertPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success"`
	PermissionId  string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id"`
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPermissionResponse) Reset() {
	*x = UpsertPermissionResponse{}
	mi := &file_auth_service_permission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPermissionResponse) ProtoMessage() {}

func (x *UpsertPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPermissionResponse.ProtoReflect.Descriptor instead.
func (*UpsertPermissionResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_proto_rawDescGZIP(), []int{9}
}

func (x *UpsertPermissionResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *UpsertPermissionResponse) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *UpsertPermissionResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeletePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionId  string                 `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_auth_service_permission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

type DeletePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	Error         *common.Error          `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionResponse) Reset() {
	*x = DeletePermissionResponse{}
	mi := &file_auth_service_permission_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionResponse) ProtoMessage() {}

func (x *DeletePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionResponse.ProtoReflect.Descriptor instead.
func (*DeletePermissionResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_proto_rawDescGZIP(), []int{11}
}

func (x *DeletePermissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeletePermissionResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DeletePermissionResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_auth_service_permission_proto protoreflect.FileDescriptor

const file_auth_service_permission_proto_rawDesc = "" +
	"\n" +
	"\x1dauth_service/permission.proto\x12\x04auth\x1a\x1eauth_service/common.auth.proto\x1a\x17common/pagination.proto\x1a\x12common/error.proto\"\x15\n" +
	"\x13GetResourcesRequest\"x\n" +
	"\x14GetResourcesResponse\x12,\n" +
	"\tresources\x18\x01 \x03(\v2\x0e.auth.ResourceR\tresources\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\r.common.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"4\n" +
	"\x11GetActionsRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"p\n" +
	"\x12GetActionsResponse\x12&\n" +
	"\aactions\x18\x01 \x03(\v2\f.auth.ActionR\aactions\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\r.common.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x82\x01\n" +
	"\x15GetPermissionsRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x120\n" +
	"\n" +
	"page_query\x18\x02 \x01(\v2\x11.common.PageQueryR\tpageQuery\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\"\xe8\x02\n" +
	"\x16GetPermissionsResponse\x126\n" +
	"\vpermissions\x18\x01 \x03(\v2\x14.auth.PermissionItemR\vpermissions\x12-\n" +
	"\tpage_info\x18\x02 \x01(\v2\x10.common.PageInfoR\bpageInfo\x12+\n" +
	"\x11total_permissions\x18\x03 \x01(\x05R\x10totalPermissions\x12\x12\n" +
	"\x04root\x18\x04 \x01(\x05R\x04root\x12\x19\n" +
	"\bnon_root\x18\x05 \x01(\x05R\anonRoot\x12'\n" +
	"\x0froot_percentage\x18\x06 \x01(\x01R\x0erootPercentage\x12.\n" +
	"\x13non_root_percentage\x18\a \x01(\x01R\x11nonRootPercentage\x12(\n" +
	"\x05error\x18\b \x01(\v2\r.common.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\";\n" +
	"\x14GetPermissionRequest\x12#\n" +
	"\rpermission_id\x18\x01 \x01(\tR\fpermissionId\"\x81\x01\n" +
	"\x15GetPermissionResponse\x124\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x14.auth.PermissionItemR\n" +
	"permission\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\r.common.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xcd\x01\n" +
	"\x17UpsertPermissionRequest\x12(\n" +
	"\rpermission_id\x18\x01 \x01(\tH\x00R\fpermissionId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\x12\x1f\n" +
	"\vactions_ids\x18\x05 \x03(\tR\n" +
	"actionsIdsB\x10\n" +
	"\x0e_permission_id\"\x92\x01\n" +
	"\x18UpsertPermissionResponse\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\tR\fpermissionId\x12(\n" +
	"\x05error\x18\x03 \x01(\v2\r.common.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\">\n" +
	"\x17DeletePermissionRequest\x12#\n" +
	"\rpermission_id\x18\x01 \x01(\tR\fpermissionId\"\x93\x01\n" +
	"\x18DeletePermissionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\r.common.ErrorH\x00R\x05error\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x01R\amessage\x88\x01\x01B\b\n" +
	"\x06_errorB\n" +
	"\n" +
	"\b_message2\xd8\x03\n" +
	"\x11PermissionService\x12E\n" +
	"\fGetResources\x12\x19.auth.GetResourcesRequest\x1a\x1a.auth.GetResourcesResponse\x12?\n" +
	"\n" +
	"GetActions\x12\x17.auth.GetActionsRequest\x1a\x18.auth.GetActionsResponse\x12K\n" +
	"\x0eGetPermissions\x12\x1b.auth.GetPermissionsRequest\x1a\x1c.auth.GetPermissionsResponse\x12H\n" +
	"\rGetPermission\x12\x1a.auth.GetPermissionRequest\x1a\x1b.auth.GetPermissionResponse\x12Q\n" +
	"\x10UpsertPermission\x12\x1d.auth.UpsertPermissionRequest\x1a\x1e.auth.UpsertPermissionResponse\x12Q\n" +
	"\x10DeletePermission\x12\x1d.auth.DeletePermissionRequest\x1a\x1e.auth.DeletePermissionResponseB\fZ\n" +
	"proto/authb\x06proto3"

var (
	file_auth_service_permission_proto_rawDescOnce sync.Once
	file_auth_service_permission_proto_rawDescData []byte
)

func file_auth_service_permission_proto_rawDescGZIP() []byte {
	file_auth_service_permission_proto_rawDescOnce.Do(func() {
		file_auth_service_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_service_permission_proto_rawDesc), len(file_auth_service_permission_proto_rawDesc)))
	})
	return file_auth_service_permission_proto_rawDescData
}

var file_auth_service_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_auth_service_permission_proto_goTypes = []any{
	(*GetResourcesRequest)(nil),      // 0: auth.GetResourcesRequest
	(*GetResourcesResponse)(nil),     // 1: auth.GetResourcesResponse
	(*GetActionsRequest)(nil),        // 2: auth.GetActionsRequest
	(*GetActionsResponse)(nil),       // 3: auth.GetActionsResponse
	(*GetPermissionsRequest)(nil),    // 4: auth.GetPermissionsRequest
	(*GetPermissionsResponse)(nil),   // 5: auth.GetPermissionsResponse
	(*GetPermissionRequest)(nil),     // 6: auth.GetPermissionRequest
	(*GetPermissionResponse)(nil),    // 7: auth.GetPermissionResponse
	(*UpsertPermissionRequest)(nil),  // 8: auth.UpsertPermissionRequest
	(*UpsertPermissionResponse)(nil), // 9: auth.UpsertPermissionResponse
	(*DeletePermissionRequest)(nil),  // 10: auth.DeletePermissionRequest
	(*DeletePermissionResponse)(nil), // 11: auth.DeletePermissionResponse
	(*Resource)(nil),                 // 12: auth.Resource
	(*common.Error)(nil),             // 13: common.Error
	(*Action)(nil),                   // 14: auth.Action
	(*common.PageQuery)(nil),         // 15: common.PageQuery
	(*PermissionItem)(nil),           // 16: auth.PermissionItem
	(*common.PageInfo)(nil),          // 17: common.PageInfo
}
var file_auth_service_permission_proto_depIdxs = []int32{
	12, // 0: auth.GetResourcesResponse.resources:type_name -> auth.Resource
	13, // 1: auth.GetResourcesResponse.error:type_name -> common.Error
	14, // 2: auth.GetActionsResponse.actions:type_name -> auth.Action
	13, // 3: auth.GetActionsResponse.error:type_name -> common.Error
	15, // 4: auth.GetPermissionsRequest.page_query:type_name -> common.PageQuery
	16, // 5: auth.GetPermissionsResponse.permissions:type_name -> auth.PermissionItem
	17, // 6: auth.GetPermissionsResponse.page_info:type_name -> common.PageInfo
	13, // 7: auth.GetPermissionsResponse.error:type_name -> common.Error
	16, // 8: auth.GetPermissionResponse.permission:type_name -> auth.PermissionItem
	13, // 9: auth.GetPermissionResponse.error:type_name -> common.Error
	13, // 10: auth.UpsertPermissionResponse.error:type_name -> common.Error
	13, // 11: auth.DeletePermissionResponse.error:type_name -> common.Error
	0,  // 12: auth.PermissionService.GetResources:input_type -> auth.GetResourcesRequest
	2,  // 13: auth.PermissionService.GetActions:input_type -> auth.GetActionsRequest
	4,  // 14: auth.PermissionService.GetPermissions:input_type -> auth.GetPermissionsRequest
	6,  // 15: auth.PermissionService.GetPermission:input_type -> auth.GetPermissionRequest
	8,  // 16: auth.PermissionService.UpsertPermission:input_type -> auth.UpsertPermissionRequest
	10, // 17: auth.PermissionService.DeletePermission:input_type -> auth.DeletePermissionRequest
	1,  // 18: auth.PermissionService.GetResources:output_type -> auth.GetResourcesResponse
	3,  // 19: auth.PermissionService.GetActions:output_type -> auth.GetActionsResponse
	5,  // 20: auth.PermissionService.GetPermissions:output_type -> auth.GetPermissionsResponse
	7,  // 21: auth.PermissionService.GetPermission:output_type -> auth.GetPermissionResponse
	9,  // 22: auth.PermissionService.UpsertPermission:output_type -> auth.UpsertPermissionResponse
	11, // 23: auth.PermissionService.DeletePermission:output_type -> auth.DeletePermissionResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_auth_service_permission_proto_init() }
func file_auth_service_permission_proto_init() {
	if File_auth_service_permission_proto != nil {
		return
	}
	file_auth_service_common_auth_proto_init()
	file_auth_service_permission_proto_msgTypes[1].OneofWrappers = []any{}
	file_auth_service_permission_proto_msgTypes[3].OneofWrappers = []any{}
	file_auth_service_permission_proto_msgTypes[5].OneofWrappers = []any{}
	file_auth_service_permission_proto_msgTypes[7].OneofWrappers = []any{}
	file_auth_service_permission_proto_msgTypes[8].OneofWrappers = []any{}
	file_auth_service_permission_proto_msgTypes[9].OneofWrappers = []any{}
	file_auth_service_permission_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_service_permission_proto_rawDesc), len(file_auth_service_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_service_permission_proto_goTypes,
		DependencyIndexes: file_auth_service_permission_proto_depIdxs,
		MessageInfos:      file_auth_service_permission_proto_msgTypes,
	}.Build()
	File_auth_service_permission_proto = out.File
	file_auth_service_permission_proto_goTypes = nil
	file_auth_service_permission_proto_depIdxs = nil
}
