// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: auth_service/user.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "schedule_gateway/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignRoleToUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	RoleIds       []string               `protobuf:"bytes,2,rep,name=role_ids,json=roleIds,proto3" json:"role_ids"`
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleToUserRequest) Reset() {
	*x = AssignRoleToUserRequest{}
	mi := &file_auth_service_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleToUserRequest) ProtoMessage() {}

func (x *AssignRoleToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleToUserRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleToUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_user_proto_rawDescGZIP(), []int{0}
}

func (x *AssignRoleToUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignRoleToUserRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *AssignRoleToUserRequest) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_auth_service_user_proto protoreflect.FileDescriptor

const file_auth_service_user_proto_rawDesc = "" +
	"\n" +
	"\x17auth_service/user.proto\x12\x04auth\x1a\x12common/error.proto\x1a\x13common/common.proto\"r\n" +
	"\x17AssignRoleToUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\tR\aroleIds\x12#\n" +
	"\x05error\x18\x03 \x01(\v2\r.common.ErrorR\x05error2W\n" +
	"\vUserService\x12H\n" +
	"\x10AssignRoleToUser\x12\x1d.auth.AssignRoleToUserRequest\x1a\x15.common.EmptyResponseB\fZ\n" +
	"proto/authb\x06proto3"

var (
	file_auth_service_user_proto_rawDescOnce sync.Once
	file_auth_service_user_proto_rawDescData []byte
)

func file_auth_service_user_proto_rawDescGZIP() []byte {
	file_auth_service_user_proto_rawDescOnce.Do(func() {
		file_auth_service_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_service_user_proto_rawDesc), len(file_auth_service_user_proto_rawDesc)))
	})
	return file_auth_service_user_proto_rawDescData
}

var file_auth_service_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_service_user_proto_goTypes = []any{
	(*AssignRoleToUserRequest)(nil), // 0: auth.AssignRoleToUserRequest
	(*common.Error)(nil),            // 1: common.Error
	(*common.EmptyResponse)(nil),    // 2: common.EmptyResponse
}
var file_auth_service_user_proto_depIdxs = []int32{
	1, // 0: auth.AssignRoleToUserRequest.error:type_name -> common.Error
	0, // 1: auth.UserService.AssignRoleToUser:input_type -> auth.AssignRoleToUserRequest
	2, // 2: auth.UserService.AssignRoleToUser:output_type -> common.EmptyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_service_user_proto_init() }
func file_auth_service_user_proto_init() {
	if File_auth_service_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_service_user_proto_rawDesc), len(file_auth_service_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_service_user_proto_goTypes,
		DependencyIndexes: file_auth_service_user_proto_depIdxs,
		MessageInfos:      file_auth_service_user_proto_msgTypes,
	}.Build()
	File_auth_service_user_proto = out.File
	file_auth_service_user_proto_goTypes = nil
	file_auth_service_user_proto_depIdxs = nil
}
