server:
  port: 8080
  host: 0.0.0.0
  mode: development

log:
  level: DEBUG
  file_log_path: ./storage/logs/
  max_size: 500
  max_backups: 3
  max_age: 15
  compress: true


auth_service:
  host: 0.0.0.0
  port: 50000

user_service:
  host: 0.0.0.0
  port: 50001
