// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: personal_schedule_service/common.schedule.proto

package personal_schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key"`
	Meaning       string                 `protobuf:"bytes,4,opt,name=meaning,proto3" json:"meaning"`
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color"`
	LabelType     int32                  `protobuf:"varint,7,opt,name=label_type,json=labelType,proto3" json:"label_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_common_schedule_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Label) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Label) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Label) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *Label) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Label) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Label) GetLabelType() int32 {
	if x != nil {
		return x.LabelType
	}
	return 0
}

type LabelPerType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type"`
	Labels        []*Label               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelPerType) Reset() {
	*x = LabelPerType{}
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelPerType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelPerType) ProtoMessage() {}

func (x *LabelPerType) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelPerType.ProtoReflect.Descriptor instead.
func (*LabelPerType) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_common_schedule_proto_rawDescGZIP(), []int{1}
}

func (x *LabelPerType) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *LabelPerType) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

type LabelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color"`
	LabelType     int32                  `protobuf:"varint,5,opt,name=label_type,json=labelType,proto3" json:"label_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelInfo) Reset() {
	*x = LabelInfo{}
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelInfo) ProtoMessage() {}

func (x *LabelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelInfo.ProtoReflect.Descriptor instead.
func (*LabelInfo) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_common_schedule_proto_rawDescGZIP(), []int{2}
}

func (x *LabelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LabelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabelInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LabelInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *LabelInfo) GetLabelType() int32 {
	if x != nil {
		return x.LabelType
	}
	return 0
}

type GoalLabels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        []*LabelInfo           `protobuf:"bytes,1,rep,name=status,proto3" json:"status"`
	Difficulty    []*LabelInfo           `protobuf:"bytes,2,rep,name=difficulty,proto3" json:"difficulty"`
	Priority      []*LabelInfo           `protobuf:"bytes,3,rep,name=priority,proto3" json:"priority"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoalLabels) Reset() {
	*x = GoalLabels{}
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalLabels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalLabels) ProtoMessage() {}

func (x *GoalLabels) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalLabels.ProtoReflect.Descriptor instead.
func (*GoalLabels) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_common_schedule_proto_rawDescGZIP(), []int{3}
}

func (x *GoalLabels) GetStatus() []*LabelInfo {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GoalLabels) GetDifficulty() []*LabelInfo {
	if x != nil {
		return x.Difficulty
	}
	return nil
}

func (x *GoalLabels) GetPriority() []*LabelInfo {
	if x != nil {
		return x.Priority
	}
	return nil
}

type Goal struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	ShortDescriptions   string                 `protobuf:"bytes,3,opt,name=short_descriptions,json=shortDescriptions,proto3" json:"short_descriptions"`
	DetailedDescription string                 `protobuf:"bytes,4,opt,name=detailed_description,json=detailedDescription,proto3" json:"detailed_description"`
	StartDate           int64                  `protobuf:"varint,5,opt,name=start_date,json=startDate,proto3" json:"start_date"`
	EndDate             int64                  `protobuf:"varint,6,opt,name=end_date,json=endDate,proto3" json:"end_date"`
	GoalLabels          *GoalLabels            `protobuf:"bytes,7,opt,name=goalLabels,proto3" json:"goalLabels"`
	Category            []*LabelInfo           `protobuf:"bytes,8,rep,name=category,proto3" json:"category"`
	UserId              string                 `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Goal) Reset() {
	*x = Goal{}
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goal) ProtoMessage() {}

func (x *Goal) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goal.ProtoReflect.Descriptor instead.
func (*Goal) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_common_schedule_proto_rawDescGZIP(), []int{4}
}

func (x *Goal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Goal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Goal) GetShortDescriptions() string {
	if x != nil {
		return x.ShortDescriptions
	}
	return ""
}

func (x *Goal) GetDetailedDescription() string {
	if x != nil {
		return x.DetailedDescription
	}
	return ""
}

func (x *Goal) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *Goal) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *Goal) GetGoalLabels() *GoalLabels {
	if x != nil {
		return x.GoalLabels
	}
	return nil
}

func (x *Goal) GetCategory() []*LabelInfo {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Goal) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GoalTaskPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	IsCompleted   bool                   `protobuf:"varint,3,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoalTaskPayload) Reset() {
	*x = GoalTaskPayload{}
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalTaskPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalTaskPayload) ProtoMessage() {}

func (x *GoalTaskPayload) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalTaskPayload.ProtoReflect.Descriptor instead.
func (*GoalTaskPayload) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_common_schedule_proto_rawDescGZIP(), []int{5}
}

func (x *GoalTaskPayload) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *GoalTaskPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoalTaskPayload) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

type GoalLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        []*LabelInfo           `protobuf:"bytes,1,rep,name=status,proto3" json:"status"`
	Difficulty    []*LabelInfo           `protobuf:"bytes,2,rep,name=difficulty,proto3" json:"difficulty"`
	Priority      []*LabelInfo           `protobuf:"bytes,3,rep,name=priority,proto3" json:"priority"`
	Category      []*LabelInfo           `protobuf:"bytes,4,rep,name=category,proto3" json:"category"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoalLabel) Reset() {
	*x = GoalLabel{}
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalLabel) ProtoMessage() {}

func (x *GoalLabel) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalLabel.ProtoReflect.Descriptor instead.
func (*GoalLabel) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_common_schedule_proto_rawDescGZIP(), []int{6}
}

func (x *GoalLabel) GetStatus() []*LabelInfo {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GoalLabel) GetDifficulty() []*LabelInfo {
	if x != nil {
		return x.Difficulty
	}
	return nil
}

func (x *GoalLabel) GetPriority() []*LabelInfo {
	if x != nil {
		return x.Priority
	}
	return nil
}

func (x *GoalLabel) GetCategory() []*LabelInfo {
	if x != nil {
		return x.Category
	}
	return nil
}

type GoalDetail struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	ShortDescriptions   string                 `protobuf:"bytes,3,opt,name=short_descriptions,json=shortDescriptions,proto3" json:"short_descriptions"`
	DetailedDescription string                 `protobuf:"bytes,4,opt,name=detailed_description,json=detailedDescription,proto3" json:"detailed_description"`
	StartDate           int64                  `protobuf:"varint,5,opt,name=start_date,json=startDate,proto3" json:"start_date"`
	EndDate             int64                  `protobuf:"varint,6,opt,name=end_date,json=endDate,proto3" json:"end_date"`
	GoalLabels          *GoalLabel             `protobuf:"bytes,7,opt,name=goalLabels,proto3" json:"goalLabels"`
	UserId              string                 `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Tasks               []*GoalTaskPayload     `protobuf:"bytes,10,rep,name=tasks,proto3" json:"tasks"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GoalDetail) Reset() {
	*x = GoalDetail{}
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalDetail) ProtoMessage() {}

func (x *GoalDetail) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalDetail.ProtoReflect.Descriptor instead.
func (*GoalDetail) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_common_schedule_proto_rawDescGZIP(), []int{7}
}

func (x *GoalDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GoalDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoalDetail) GetShortDescriptions() string {
	if x != nil {
		return x.ShortDescriptions
	}
	return ""
}

func (x *GoalDetail) GetDetailedDescription() string {
	if x != nil {
		return x.DetailedDescription
	}
	return ""
}

func (x *GoalDetail) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *GoalDetail) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *GoalDetail) GetGoalLabels() *GoalLabel {
	if x != nil {
		return x.GoalLabels
	}
	return nil
}

func (x *GoalDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GoalDetail) GetTasks() []*GoalTaskPayload {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type SubTaskPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	IsCompleted   bool                   `protobuf:"varint,3,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubTaskPayload) Reset() {
	*x = SubTaskPayload{}
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubTaskPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubTaskPayload) ProtoMessage() {}

func (x *SubTaskPayload) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_common_schedule_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubTaskPayload.ProtoReflect.Descriptor instead.
func (*SubTaskPayload) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_common_schedule_proto_rawDescGZIP(), []int{8}
}

func (x *SubTaskPayload) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *SubTaskPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubTaskPayload) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

var File_personal_schedule_service_common_schedule_proto protoreflect.FileDescriptor

const file_personal_schedule_service_common_schedule_proto_rawDesc = "" +
	"\n" +
	"/personal_schedule_service/common.schedule.proto\x12\x11personal_schedule\"\xa0\x01\n" +
	"\x05Label\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x18\n" +
	"\ameaning\x18\x04 \x01(\tR\ameaning\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12\x1d\n" +
	"\n" +
	"label_type\x18\a \x01(\x05R\tlabelType\"T\n" +
	"\fLabelPerType\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x120\n" +
	"\x06labels\x18\x02 \x03(\v2\x18.personal_schedule.LabelR\x06labels\"v\n" +
	"\tLabelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x1d\n" +
	"\n" +
	"label_type\x18\x05 \x01(\x05R\tlabelType\"\xba\x01\n" +
	"\n" +
	"GoalLabels\x124\n" +
	"\x06status\x18\x01 \x03(\v2\x1c.personal_schedule.LabelInfoR\x06status\x12<\n" +
	"\n" +
	"difficulty\x18\x02 \x03(\v2\x1c.personal_schedule.LabelInfoR\n" +
	"difficulty\x128\n" +
	"\bpriority\x18\x03 \x03(\v2\x1c.personal_schedule.LabelInfoR\bpriority\"\xd8\x02\n" +
	"\x04Goal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x12short_descriptions\x18\x03 \x01(\tR\x11shortDescriptions\x121\n" +
	"\x14detailed_description\x18\x04 \x01(\tR\x13detailedDescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\x03R\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\x03R\aendDate\x12=\n" +
	"\n" +
	"goalLabels\x18\a \x01(\v2\x1d.personal_schedule.GoalLabelsR\n" +
	"goalLabels\x128\n" +
	"\bcategory\x18\b \x03(\v2\x1c.personal_schedule.LabelInfoR\bcategory\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\"d\n" +
	"\x0fGoalTaskPayload\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fis_completed\x18\x03 \x01(\bR\visCompletedB\x05\n" +
	"\x03_id\"\xf3\x01\n" +
	"\tGoalLabel\x124\n" +
	"\x06status\x18\x01 \x03(\v2\x1c.personal_schedule.LabelInfoR\x06status\x12<\n" +
	"\n" +
	"difficulty\x18\x02 \x03(\v2\x1c.personal_schedule.LabelInfoR\n" +
	"difficulty\x128\n" +
	"\bpriority\x18\x03 \x03(\v2\x1c.personal_schedule.LabelInfoR\bpriority\x128\n" +
	"\bcategory\x18\x04 \x03(\v2\x1c.personal_schedule.LabelInfoR\bcategory\"\xdd\x02\n" +
	"\n" +
	"GoalDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x12short_descriptions\x18\x03 \x01(\tR\x11shortDescriptions\x121\n" +
	"\x14detailed_description\x18\x04 \x01(\tR\x13detailedDescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\x03R\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\x03R\aendDate\x12<\n" +
	"\n" +
	"goalLabels\x18\a \x01(\v2\x1c.personal_schedule.GoalLabelR\n" +
	"goalLabels\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x128\n" +
	"\x05tasks\x18\n" +
	" \x03(\v2\".personal_schedule.GoalTaskPayloadR\x05tasks\"c\n" +
	"\x0eSubTaskPayload\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fis_completed\x18\x03 \x01(\bR\visCompletedB\x05\n" +
	"\x03_idB\x19Z\x17proto/personal_scheduleb\x06proto3"

var (
	file_personal_schedule_service_common_schedule_proto_rawDescOnce sync.Once
	file_personal_schedule_service_common_schedule_proto_rawDescData []byte
)

func file_personal_schedule_service_common_schedule_proto_rawDescGZIP() []byte {
	file_personal_schedule_service_common_schedule_proto_rawDescOnce.Do(func() {
		file_personal_schedule_service_common_schedule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_personal_schedule_service_common_schedule_proto_rawDesc), len(file_personal_schedule_service_common_schedule_proto_rawDesc)))
	})
	return file_personal_schedule_service_common_schedule_proto_rawDescData
}

var file_personal_schedule_service_common_schedule_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_personal_schedule_service_common_schedule_proto_goTypes = []any{
	(*Label)(nil),           // 0: personal_schedule.Label
	(*LabelPerType)(nil),    // 1: personal_schedule.LabelPerType
	(*LabelInfo)(nil),       // 2: personal_schedule.LabelInfo
	(*GoalLabels)(nil),      // 3: personal_schedule.GoalLabels
	(*Goal)(nil),            // 4: personal_schedule.Goal
	(*GoalTaskPayload)(nil), // 5: personal_schedule.GoalTaskPayload
	(*GoalLabel)(nil),       // 6: personal_schedule.GoalLabel
	(*GoalDetail)(nil),      // 7: personal_schedule.GoalDetail
	(*SubTaskPayload)(nil),  // 8: personal_schedule.SubTaskPayload
}
var file_personal_schedule_service_common_schedule_proto_depIdxs = []int32{
	0,  // 0: personal_schedule.LabelPerType.labels:type_name -> personal_schedule.Label
	2,  // 1: personal_schedule.GoalLabels.status:type_name -> personal_schedule.LabelInfo
	2,  // 2: personal_schedule.GoalLabels.difficulty:type_name -> personal_schedule.LabelInfo
	2,  // 3: personal_schedule.GoalLabels.priority:type_name -> personal_schedule.LabelInfo
	3,  // 4: personal_schedule.Goal.goalLabels:type_name -> personal_schedule.GoalLabels
	2,  // 5: personal_schedule.Goal.category:type_name -> personal_schedule.LabelInfo
	2,  // 6: personal_schedule.GoalLabel.status:type_name -> personal_schedule.LabelInfo
	2,  // 7: personal_schedule.GoalLabel.difficulty:type_name -> personal_schedule.LabelInfo
	2,  // 8: personal_schedule.GoalLabel.priority:type_name -> personal_schedule.LabelInfo
	2,  // 9: personal_schedule.GoalLabel.category:type_name -> personal_schedule.LabelInfo
	6,  // 10: personal_schedule.GoalDetail.goalLabels:type_name -> personal_schedule.GoalLabel
	5,  // 11: personal_schedule.GoalDetail.tasks:type_name -> personal_schedule.GoalTaskPayload
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_personal_schedule_service_common_schedule_proto_init() }
func file_personal_schedule_service_common_schedule_proto_init() {
	if File_personal_schedule_service_common_schedule_proto != nil {
		return
	}
	file_personal_schedule_service_common_schedule_proto_msgTypes[5].OneofWrappers = []any{}
	file_personal_schedule_service_common_schedule_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_personal_schedule_service_common_schedule_proto_rawDesc), len(file_personal_schedule_service_common_schedule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_personal_schedule_service_common_schedule_proto_goTypes,
		DependencyIndexes: file_personal_schedule_service_common_schedule_proto_depIdxs,
		MessageInfos:      file_personal_schedule_service_common_schedule_proto_msgTypes,
	}.Build()
	File_personal_schedule_service_common_schedule_proto = out.File
	file_personal_schedule_service_common_schedule_proto_goTypes = nil
	file_personal_schedule_service_common_schedule_proto_depIdxs = nil
}
