// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: personal_schedule_service/goal.proto

package personal_schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "schedule_gateway/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGoalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search"`
	StatusId      string                 `protobuf:"bytes,3,opt,name=status_id,json=statusId,proto3" json:"status_id"`
	PageQuery     *common.PageQuery      `protobuf:"bytes,4,opt,name=page_query,json=pageQuery,proto3" json:"page_query"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoalsRequest) Reset() {
	*x = GetGoalsRequest{}
	mi := &file_personal_schedule_service_goal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoalsRequest) ProtoMessage() {}

func (x *GetGoalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_goal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoalsRequest.ProtoReflect.Descriptor instead.
func (*GetGoalsRequest) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_goal_proto_rawDescGZIP(), []int{0}
}

func (x *GetGoalsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetGoalsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetGoalsRequest) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

func (x *GetGoalsRequest) GetPageQuery() *common.PageQuery {
	if x != nil {
		return x.PageQuery
	}
	return nil
}

type GetGoalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goals         []*Goal                `protobuf:"bytes,1,rep,name=goals,proto3" json:"goals"`
	PageInfo      *common.PageInfo       `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info"`
	TotalGoals    int32                  `protobuf:"varint,3,opt,name=total_goals,json=totalGoals,proto3" json:"total_goals"`
	Error         *common.Error          `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoalsResponse) Reset() {
	*x = GetGoalsResponse{}
	mi := &file_personal_schedule_service_goal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoalsResponse) ProtoMessage() {}

func (x *GetGoalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_goal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoalsResponse.ProtoReflect.Descriptor instead.
func (*GetGoalsResponse) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_goal_proto_rawDescGZIP(), []int{1}
}

func (x *GetGoalsResponse) GetGoals() []*Goal {
	if x != nil {
		return x.Goals
	}
	return nil
}

func (x *GetGoalsResponse) GetPageInfo() *common.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *GetGoalsResponse) GetTotalGoals() int32 {
	if x != nil {
		return x.TotalGoals
	}
	return 0
}

func (x *GetGoalsResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_personal_schedule_service_goal_proto protoreflect.FileDescriptor

const file_personal_schedule_service_goal_proto_rawDesc = "" +
	"\n" +
	"$personal_schedule_service/goal.proto\x12\x11personal_schedule\x1a/personal_schedule_service/common.schedule.proto\x1a\x12common/error.proto\x1a\x17common/pagination.proto\x1a\x13common/common.proto\"\x91\x01\n" +
	"\x0fGetGoalsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x1b\n" +
	"\tstatus_id\x18\x03 \x01(\tR\bstatusId\x120\n" +
	"\n" +
	"page_query\x18\x04 \x01(\v2\x11.common.PageQueryR\tpageQuery\"\xc5\x01\n" +
	"\x10GetGoalsResponse\x12-\n" +
	"\x05goals\x18\x01 \x03(\v2\x17.personal_schedule.GoalR\x05goals\x12-\n" +
	"\tpage_info\x18\x02 \x01(\v2\x10.common.PageInfoR\bpageInfo\x12\x1f\n" +
	"\vtotal_goals\x18\x03 \x01(\x05R\n" +
	"totalGoals\x12(\n" +
	"\x05error\x18\x04 \x01(\v2\r.common.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2b\n" +
	"\vGoalService\x12S\n" +
	"\bGetGoals\x12\".personal_schedule.GetGoalsRequest\x1a#.personal_schedule.GetGoalsResponseB\x19Z\x17proto/personal_scheduleb\x06proto3"

var (
	file_personal_schedule_service_goal_proto_rawDescOnce sync.Once
	file_personal_schedule_service_goal_proto_rawDescData []byte
)

func file_personal_schedule_service_goal_proto_rawDescGZIP() []byte {
	file_personal_schedule_service_goal_proto_rawDescOnce.Do(func() {
		file_personal_schedule_service_goal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_personal_schedule_service_goal_proto_rawDesc), len(file_personal_schedule_service_goal_proto_rawDesc)))
	})
	return file_personal_schedule_service_goal_proto_rawDescData
}

var file_personal_schedule_service_goal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_personal_schedule_service_goal_proto_goTypes = []any{
	(*GetGoalsRequest)(nil),  // 0: personal_schedule.GetGoalsRequest
	(*GetGoalsResponse)(nil), // 1: personal_schedule.GetGoalsResponse
	(*common.PageQuery)(nil), // 2: common.PageQuery
	(*Goal)(nil),             // 3: personal_schedule.Goal
	(*common.PageInfo)(nil),  // 4: common.PageInfo
	(*common.Error)(nil),     // 5: common.Error
}
var file_personal_schedule_service_goal_proto_depIdxs = []int32{
	2, // 0: personal_schedule.GetGoalsRequest.page_query:type_name -> common.PageQuery
	3, // 1: personal_schedule.GetGoalsResponse.goals:type_name -> personal_schedule.Goal
	4, // 2: personal_schedule.GetGoalsResponse.page_info:type_name -> common.PageInfo
	5, // 3: personal_schedule.GetGoalsResponse.error:type_name -> common.Error
	0, // 4: personal_schedule.GoalService.GetGoals:input_type -> personal_schedule.GetGoalsRequest
	1, // 5: personal_schedule.GoalService.GetGoals:output_type -> personal_schedule.GetGoalsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_personal_schedule_service_goal_proto_init() }
func file_personal_schedule_service_goal_proto_init() {
	if File_personal_schedule_service_goal_proto != nil {
		return
	}
	file_personal_schedule_service_common_schedule_proto_init()
	file_personal_schedule_service_goal_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_personal_schedule_service_goal_proto_rawDesc), len(file_personal_schedule_service_goal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_personal_schedule_service_goal_proto_goTypes,
		DependencyIndexes: file_personal_schedule_service_goal_proto_depIdxs,
		MessageInfos:      file_personal_schedule_service_goal_proto_msgTypes,
	}.Build()
	File_personal_schedule_service_goal_proto = out.File
	file_personal_schedule_service_goal_proto_goTypes = nil
	file_personal_schedule_service_goal_proto_depIdxs = nil
}
