// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: personal_schedule_service/label.proto

package personal_schedule

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "schedule_gateway/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LabelService_GetLabelPerTypes_FullMethodName   = "/personal_schedule.LabelService/GetLabelPerTypes"
	LabelService_GetLabelsByTypeIDs_FullMethodName = "/personal_schedule.LabelService/GetLabelsByTypeIDs"
	LabelService_GetDefaultLabel_FullMethodName    = "/personal_schedule.LabelService/GetDefaultLabel"
)

// LabelServiceClient is the client API for LabelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LabelServiceClient interface {
	GetLabelPerTypes(ctx context.Context, in *common.EmptyRequest, opts ...grpc.CallOption) (*GetLabelPerTypesResponse, error)
	GetLabelsByTypeIDs(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*GetLabelsByTypeIDsResponse, error)
	GetDefaultLabel(ctx context.Context, in *common.EmptyRequest, opts ...grpc.CallOption) (*GetDefaultLabelResponse, error)
}

type labelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLabelServiceClient(cc grpc.ClientConnInterface) LabelServiceClient {
	return &labelServiceClient{cc}
}

func (c *labelServiceClient) GetLabelPerTypes(ctx context.Context, in *common.EmptyRequest, opts ...grpc.CallOption) (*GetLabelPerTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLabelPerTypesResponse)
	err := c.cc.Invoke(ctx, LabelService_GetLabelPerTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labelServiceClient) GetLabelsByTypeIDs(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*GetLabelsByTypeIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLabelsByTypeIDsResponse)
	err := c.cc.Invoke(ctx, LabelService_GetLabelsByTypeIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labelServiceClient) GetDefaultLabel(ctx context.Context, in *common.EmptyRequest, opts ...grpc.CallOption) (*GetDefaultLabelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDefaultLabelResponse)
	err := c.cc.Invoke(ctx, LabelService_GetDefaultLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LabelServiceServer is the server API for LabelService service.
// All implementations must embed UnimplementedLabelServiceServer
// for forward compatibility.
type LabelServiceServer interface {
	GetLabelPerTypes(context.Context, *common.EmptyRequest) (*GetLabelPerTypesResponse, error)
	GetLabelsByTypeIDs(context.Context, *common.IDRequest) (*GetLabelsByTypeIDsResponse, error)
	GetDefaultLabel(context.Context, *common.EmptyRequest) (*GetDefaultLabelResponse, error)
	mustEmbedUnimplementedLabelServiceServer()
}

// UnimplementedLabelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLabelServiceServer struct{}

func (UnimplementedLabelServiceServer) GetLabelPerTypes(context.Context, *common.EmptyRequest) (*GetLabelPerTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLabelPerTypes not implemented")
}
func (UnimplementedLabelServiceServer) GetLabelsByTypeIDs(context.Context, *common.IDRequest) (*GetLabelsByTypeIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLabelsByTypeIDs not implemented")
}
func (UnimplementedLabelServiceServer) GetDefaultLabel(context.Context, *common.EmptyRequest) (*GetDefaultLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefaultLabel not implemented")
}
func (UnimplementedLabelServiceServer) mustEmbedUnimplementedLabelServiceServer() {}
func (UnimplementedLabelServiceServer) testEmbeddedByValue()                      {}

// UnsafeLabelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LabelServiceServer will
// result in compilation errors.
type UnsafeLabelServiceServer interface {
	mustEmbedUnimplementedLabelServiceServer()
}

func RegisterLabelServiceServer(s grpc.ServiceRegistrar, srv LabelServiceServer) {
	// If the following call pancis, it indicates UnimplementedLabelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LabelService_ServiceDesc, srv)
}

func _LabelService_GetLabelPerTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabelServiceServer).GetLabelPerTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LabelService_GetLabelPerTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabelServiceServer).GetLabelPerTypes(ctx, req.(*common.EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabelService_GetLabelsByTypeIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabelServiceServer).GetLabelsByTypeIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LabelService_GetLabelsByTypeIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabelServiceServer).GetLabelsByTypeIDs(ctx, req.(*common.IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabelService_GetDefaultLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabelServiceServer).GetDefaultLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LabelService_GetDefaultLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabelServiceServer).GetDefaultLabel(ctx, req.(*common.EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LabelService_ServiceDesc is the grpc.ServiceDesc for LabelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LabelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "personal_schedule.LabelService",
	HandlerType: (*LabelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLabelPerTypes",
			Handler:    _LabelService_GetLabelPerTypes_Handler,
		},
		{
			MethodName: "GetLabelsByTypeIDs",
			Handler:    _LabelService_GetLabelsByTypeIDs_Handler,
		},
		{
			MethodName: "GetDefaultLabel",
			Handler:    _LabelService_GetDefaultLabel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "personal_schedule_service/label.proto",
}
