// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: personal_schedule_service/work.proto

package personal_schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "schedule_gateway/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertWorkRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Id                  *string                `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	ShortDescriptions   *string                `protobuf:"bytes,4,opt,name=short_descriptions,json=shortDescriptions,proto3,oneof" json:"short_descriptions"`
	DetailedDescription *string                `protobuf:"bytes,5,opt,name=detailed_description,json=detailedDescription,proto3,oneof" json:"detailed_description"`
	StartDate           *int64                 `protobuf:"varint,6,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date"`
	EndDate             int64                  `protobuf:"varint,7,opt,name=end_date,json=endDate,proto3" json:"end_date"`
	StatusId            string                 `protobuf:"bytes,8,opt,name=status_id,json=statusId,proto3" json:"status_id"`
	DifficultyId        string                 `protobuf:"bytes,9,opt,name=difficulty_id,json=difficultyId,proto3" json:"difficulty_id"`
	PriorityId          string                 `protobuf:"bytes,10,opt,name=priority_id,json=priorityId,proto3" json:"priority_id"`
	TypeId              string                 `protobuf:"bytes,11,opt,name=type_id,json=typeId,proto3" json:"type_id"`
	CategoryId          string                 `protobuf:"bytes,12,opt,name=category_id,json=categoryId,proto3" json:"category_id"`
	GoalId              string                 `protobuf:"bytes,13,opt,name=goal_id,json=goalId,proto3" json:"goal_id"`
	SubTasks            []*SubTaskPayload      `protobuf:"bytes,14,rep,name=sub_tasks,json=subTasks,proto3" json:"sub_tasks"`
	NotificationIds     []string               `protobuf:"bytes,15,rep,name=notification_ids,json=notificationIds,proto3" json:"notification_ids"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpsertWorkRequest) Reset() {
	*x = UpsertWorkRequest{}
	mi := &file_personal_schedule_service_work_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertWorkRequest) ProtoMessage() {}

func (x *UpsertWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_work_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertWorkRequest.ProtoReflect.Descriptor instead.
func (*UpsertWorkRequest) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_work_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertWorkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertWorkRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *UpsertWorkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertWorkRequest) GetShortDescriptions() string {
	if x != nil && x.ShortDescriptions != nil {
		return *x.ShortDescriptions
	}
	return ""
}

func (x *UpsertWorkRequest) GetDetailedDescription() string {
	if x != nil && x.DetailedDescription != nil {
		return *x.DetailedDescription
	}
	return ""
}

func (x *UpsertWorkRequest) GetStartDate() int64 {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return 0
}

func (x *UpsertWorkRequest) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *UpsertWorkRequest) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

func (x *UpsertWorkRequest) GetDifficultyId() string {
	if x != nil {
		return x.DifficultyId
	}
	return ""
}

func (x *UpsertWorkRequest) GetPriorityId() string {
	if x != nil {
		return x.PriorityId
	}
	return ""
}

func (x *UpsertWorkRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *UpsertWorkRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *UpsertWorkRequest) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

func (x *UpsertWorkRequest) GetSubTasks() []*SubTaskPayload {
	if x != nil {
		return x.SubTasks
	}
	return nil
}

func (x *UpsertWorkRequest) GetNotificationIds() []string {
	if x != nil {
		return x.NotificationIds
	}
	return nil
}

type UpsertWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Error         *common.Error          `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertWorkResponse) Reset() {
	*x = UpsertWorkResponse{}
	mi := &file_personal_schedule_service_work_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertWorkResponse) ProtoMessage() {}

func (x *UpsertWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_work_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertWorkResponse.ProtoReflect.Descriptor instead.
func (*UpsertWorkResponse) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_work_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertWorkResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *UpsertWorkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpsertWorkResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetWorksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	FromDate      *int64                 `protobuf:"varint,2,opt,name=from_date,json=fromDate,proto3,oneof" json:"from_date"`
	ToDate        *int64                 `protobuf:"varint,3,opt,name=to_date,json=toDate,proto3,oneof" json:"to_date"`
	Search        *string                `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search"`
	StatusId      *string                `protobuf:"bytes,6,opt,name=status_id,json=statusId,proto3,oneof" json:"status_id"`
	DifficultyId  *string                `protobuf:"bytes,7,opt,name=difficulty_id,json=difficultyId,proto3,oneof" json:"difficulty_id"`
	PriorityId    *string                `protobuf:"bytes,8,opt,name=priority_id,json=priorityId,proto3,oneof" json:"priority_id"`
	TypeId        *string                `protobuf:"bytes,9,opt,name=type_id,json=typeId,proto3,oneof" json:"type_id"`
	CategoryId    *string                `protobuf:"bytes,10,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorksRequest) Reset() {
	*x = GetWorksRequest{}
	mi := &file_personal_schedule_service_work_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorksRequest) ProtoMessage() {}

func (x *GetWorksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_work_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorksRequest.ProtoReflect.Descriptor instead.
func (*GetWorksRequest) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_work_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorksRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetWorksRequest) GetFromDate() int64 {
	if x != nil && x.FromDate != nil {
		return *x.FromDate
	}
	return 0
}

func (x *GetWorksRequest) GetToDate() int64 {
	if x != nil && x.ToDate != nil {
		return *x.ToDate
	}
	return 0
}

func (x *GetWorksRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *GetWorksRequest) GetStatusId() string {
	if x != nil && x.StatusId != nil {
		return *x.StatusId
	}
	return ""
}

func (x *GetWorksRequest) GetDifficultyId() string {
	if x != nil && x.DifficultyId != nil {
		return *x.DifficultyId
	}
	return ""
}

func (x *GetWorksRequest) GetPriorityId() string {
	if x != nil && x.PriorityId != nil {
		return *x.PriorityId
	}
	return ""
}

func (x *GetWorksRequest) GetTypeId() string {
	if x != nil && x.TypeId != nil {
		return *x.TypeId
	}
	return ""
}

func (x *GetWorksRequest) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

type GetWorksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Works         []*Work                `protobuf:"bytes,1,rep,name=works,proto3" json:"works"`
	Error         *common.Error          `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorksResponse) Reset() {
	*x = GetWorksResponse{}
	mi := &file_personal_schedule_service_work_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorksResponse) ProtoMessage() {}

func (x *GetWorksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_work_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorksResponse.ProtoReflect.Descriptor instead.
func (*GetWorksResponse) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_work_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorksResponse) GetWorks() []*Work {
	if x != nil {
		return x.Works
	}
	return nil
}

func (x *GetWorksResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	WorkId        string                 `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkRequest) Reset() {
	*x = GetWorkRequest{}
	mi := &file_personal_schedule_service_work_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkRequest) ProtoMessage() {}

func (x *GetWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_work_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkRequest.ProtoReflect.Descriptor instead.
func (*GetWorkRequest) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_work_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetWorkRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

type GetWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Work          *WorkDetail            `protobuf:"bytes,1,opt,name=work,proto3" json:"work"`
	Error         *common.Error          `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkResponse) Reset() {
	*x = GetWorkResponse{}
	mi := &file_personal_schedule_service_work_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkResponse) ProtoMessage() {}

func (x *GetWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_work_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkResponse.ProtoReflect.Descriptor instead.
func (*GetWorkResponse) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_work_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkResponse) GetWork() *WorkDetail {
	if x != nil {
		return x.Work
	}
	return nil
}

func (x *GetWorkResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	WorkId        string                 `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkRequest) Reset() {
	*x = DeleteWorkRequest{}
	mi := &file_personal_schedule_service_work_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkRequest) ProtoMessage() {}

func (x *DeleteWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_work_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkRequest) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_work_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteWorkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteWorkRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

type DeleteWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	Error         *common.Error          `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkResponse) Reset() {
	*x = DeleteWorkResponse{}
	mi := &file_personal_schedule_service_work_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkResponse) ProtoMessage() {}

func (x *DeleteWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_work_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkResponse) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_work_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteWorkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteWorkResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DeleteWorkResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_personal_schedule_service_work_proto protoreflect.FileDescriptor

const file_personal_schedule_service_work_proto_rawDesc = "" +
	"\n" +
	"$personal_schedule_service/work.proto\x12\x11personal_schedule\x1a/personal_schedule_service/common.schedule.proto\x1a\x12common/error.proto\x1a\x13common/common.proto\"\xe7\x04\n" +
	"\x11UpsertWorkRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x122\n" +
	"\x12short_descriptions\x18\x04 \x01(\tH\x01R\x11shortDescriptions\x88\x01\x01\x126\n" +
	"\x14detailed_description\x18\x05 \x01(\tH\x02R\x13detailedDescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_date\x18\x06 \x01(\x03H\x03R\tstartDate\x88\x01\x01\x12\x19\n" +
	"\bend_date\x18\a \x01(\x03R\aendDate\x12\x1b\n" +
	"\tstatus_id\x18\b \x01(\tR\bstatusId\x12#\n" +
	"\rdifficulty_id\x18\t \x01(\tR\fdifficultyId\x12\x1f\n" +
	"\vpriority_id\x18\n" +
	" \x01(\tR\n" +
	"priorityId\x12\x17\n" +
	"\atype_id\x18\v \x01(\tR\x06typeId\x12\x1f\n" +
	"\vcategory_id\x18\f \x01(\tR\n" +
	"categoryId\x12\x17\n" +
	"\agoal_id\x18\r \x01(\tR\x06goalId\x12>\n" +
	"\tsub_tasks\x18\x0e \x03(\v2!.personal_schedule.SubTaskPayloadR\bsubTasks\x12)\n" +
	"\x10notification_ids\x18\x0f \x03(\tR\x0fnotificationIdsB\x05\n" +
	"\x03_idB\x15\n" +
	"\x13_short_descriptionsB\x17\n" +
	"\x15_detailed_descriptionB\r\n" +
	"\v_start_date\"\x81\x01\n" +
	"\x12UpsertWorkResponse\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x05error\x18\x04 \x01(\v2\r.common.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xae\x03\n" +
	"\x0fGetWorksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\tfrom_date\x18\x02 \x01(\x03H\x00R\bfromDate\x88\x01\x01\x12\x1c\n" +
	"\ato_date\x18\x03 \x01(\x03H\x01R\x06toDate\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x04 \x01(\tH\x02R\x06search\x88\x01\x01\x12 \n" +
	"\tstatus_id\x18\x06 \x01(\tH\x03R\bstatusId\x88\x01\x01\x12(\n" +
	"\rdifficulty_id\x18\a \x01(\tH\x04R\fdifficultyId\x88\x01\x01\x12$\n" +
	"\vpriority_id\x18\b \x01(\tH\x05R\n" +
	"priorityId\x88\x01\x01\x12\x1c\n" +
	"\atype_id\x18\t \x01(\tH\x06R\x06typeId\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\n" +
	" \x01(\tH\aR\n" +
	"categoryId\x88\x01\x01B\f\n" +
	"\n" +
	"_from_dateB\n" +
	"\n" +
	"\b_to_dateB\t\n" +
	"\a_searchB\f\n" +
	"\n" +
	"_status_idB\x10\n" +
	"\x0e_difficulty_idB\x0e\n" +
	"\f_priority_idB\n" +
	"\n" +
	"\b_type_idB\x0e\n" +
	"\f_category_id\"u\n" +
	"\x10GetWorksResponse\x12-\n" +
	"\x05works\x18\x01 \x03(\v2\x17.personal_schedule.WorkR\x05works\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\r.common.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"B\n" +
	"\x0eGetWorkRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\awork_id\x18\x02 \x01(\tR\x06workId\"x\n" +
	"\x0fGetWorkResponse\x121\n" +
	"\x04work\x18\x01 \x01(\v2\x1d.personal_schedule.WorkDetailR\x04work\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\r.common.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"E\n" +
	"\x11DeleteWorkRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\awork_id\x18\x02 \x01(\tR\x06workId\"\x8d\x01\n" +
	"\x12DeleteWorkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\r.common.ErrorH\x00R\x05error\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x01R\amessage\x88\x01\x01B\b\n" +
	"\x06_errorB\n" +
	"\n" +
	"\b_message2\xea\x02\n" +
	"\vWorkService\x12Y\n" +
	"\n" +
	"UpsertWork\x12$.personal_schedule.UpsertWorkRequest\x1a%.personal_schedule.UpsertWorkResponse\x12S\n" +
	"\bGetWorks\x12\".personal_schedule.GetWorksRequest\x1a#.personal_schedule.GetWorksResponse\x12P\n" +
	"\aGetWork\x12!.personal_schedule.GetWorkRequest\x1a\".personal_schedule.GetWorkResponse\x12Y\n" +
	"\n" +
	"DeleteWork\x12$.personal_schedule.DeleteWorkRequest\x1a%.personal_schedule.DeleteWorkResponseB\x19Z\x17proto/personal_scheduleb\x06proto3"

var (
	file_personal_schedule_service_work_proto_rawDescOnce sync.Once
	file_personal_schedule_service_work_proto_rawDescData []byte
)

func file_personal_schedule_service_work_proto_rawDescGZIP() []byte {
	file_personal_schedule_service_work_proto_rawDescOnce.Do(func() {
		file_personal_schedule_service_work_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_personal_schedule_service_work_proto_rawDesc), len(file_personal_schedule_service_work_proto_rawDesc)))
	})
	return file_personal_schedule_service_work_proto_rawDescData
}

var file_personal_schedule_service_work_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_personal_schedule_service_work_proto_goTypes = []any{
	(*UpsertWorkRequest)(nil),  // 0: personal_schedule.UpsertWorkRequest
	(*UpsertWorkResponse)(nil), // 1: personal_schedule.UpsertWorkResponse
	(*GetWorksRequest)(nil),    // 2: personal_schedule.GetWorksRequest
	(*GetWorksResponse)(nil),   // 3: personal_schedule.GetWorksResponse
	(*GetWorkRequest)(nil),     // 4: personal_schedule.GetWorkRequest
	(*GetWorkResponse)(nil),    // 5: personal_schedule.GetWorkResponse
	(*DeleteWorkRequest)(nil),  // 6: personal_schedule.DeleteWorkRequest
	(*DeleteWorkResponse)(nil), // 7: personal_schedule.DeleteWorkResponse
	(*SubTaskPayload)(nil),     // 8: personal_schedule.SubTaskPayload
	(*common.Error)(nil),       // 9: common.Error
	(*Work)(nil),               // 10: personal_schedule.Work
	(*WorkDetail)(nil),         // 11: personal_schedule.WorkDetail
}
var file_personal_schedule_service_work_proto_depIdxs = []int32{
	8,  // 0: personal_schedule.UpsertWorkRequest.sub_tasks:type_name -> personal_schedule.SubTaskPayload
	9,  // 1: personal_schedule.UpsertWorkResponse.error:type_name -> common.Error
	10, // 2: personal_schedule.GetWorksResponse.works:type_name -> personal_schedule.Work
	9,  // 3: personal_schedule.GetWorksResponse.error:type_name -> common.Error
	11, // 4: personal_schedule.GetWorkResponse.work:type_name -> personal_schedule.WorkDetail
	9,  // 5: personal_schedule.GetWorkResponse.error:type_name -> common.Error
	9,  // 6: personal_schedule.DeleteWorkResponse.error:type_name -> common.Error
	0,  // 7: personal_schedule.WorkService.UpsertWork:input_type -> personal_schedule.UpsertWorkRequest
	2,  // 8: personal_schedule.WorkService.GetWorks:input_type -> personal_schedule.GetWorksRequest
	4,  // 9: personal_schedule.WorkService.GetWork:input_type -> personal_schedule.GetWorkRequest
	6,  // 10: personal_schedule.WorkService.DeleteWork:input_type -> personal_schedule.DeleteWorkRequest
	1,  // 11: personal_schedule.WorkService.UpsertWork:output_type -> personal_schedule.UpsertWorkResponse
	3,  // 12: personal_schedule.WorkService.GetWorks:output_type -> personal_schedule.GetWorksResponse
	5,  // 13: personal_schedule.WorkService.GetWork:output_type -> personal_schedule.GetWorkResponse
	7,  // 14: personal_schedule.WorkService.DeleteWork:output_type -> personal_schedule.DeleteWorkResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_personal_schedule_service_work_proto_init() }
func file_personal_schedule_service_work_proto_init() {
	if File_personal_schedule_service_work_proto != nil {
		return
	}
	file_personal_schedule_service_common_schedule_proto_init()
	file_personal_schedule_service_work_proto_msgTypes[0].OneofWrappers = []any{}
	file_personal_schedule_service_work_proto_msgTypes[1].OneofWrappers = []any{}
	file_personal_schedule_service_work_proto_msgTypes[2].OneofWrappers = []any{}
	file_personal_schedule_service_work_proto_msgTypes[3].OneofWrappers = []any{}
	file_personal_schedule_service_work_proto_msgTypes[5].OneofWrappers = []any{}
	file_personal_schedule_service_work_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_personal_schedule_service_work_proto_rawDesc), len(file_personal_schedule_service_work_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_personal_schedule_service_work_proto_goTypes,
		DependencyIndexes: file_personal_schedule_service_work_proto_depIdxs,
		MessageInfos:      file_personal_schedule_service_work_proto_msgTypes,
	}.Build()
	File_personal_schedule_service_work_proto = out.File
	file_personal_schedule_service_work_proto_goTypes = nil
	file_personal_schedule_service_work_proto_depIdxs = nil
}
