// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: personal_schedule_service/work.proto

package personal_schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "schedule_gateway/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertWorkRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Id                  *string                `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	ShortDescriptions   *string                `protobuf:"bytes,4,opt,name=short_descriptions,json=shortDescriptions,proto3,oneof" json:"short_descriptions"`
	DetailedDescription *string                `protobuf:"bytes,5,opt,name=detailed_description,json=detailedDescription,proto3,oneof" json:"detailed_description"`
	StartDate           *int64                 `protobuf:"varint,6,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date"`
	EndDate             int64                  `protobuf:"varint,7,opt,name=end_date,json=endDate,proto3" json:"end_date"`
	StatusId            string                 `protobuf:"bytes,8,opt,name=status_id,json=statusId,proto3" json:"status_id"`
	DifficultyId        string                 `protobuf:"bytes,9,opt,name=difficulty_id,json=difficultyId,proto3" json:"difficulty_id"`
	PriorityId          string                 `protobuf:"bytes,10,opt,name=priority_id,json=priorityId,proto3" json:"priority_id"`
	TypeId              string                 `protobuf:"bytes,11,opt,name=type_id,json=typeId,proto3" json:"type_id"`
	CategoryId          string                 `protobuf:"bytes,12,opt,name=category_id,json=categoryId,proto3" json:"category_id"`
	GoalId              string                 `protobuf:"bytes,13,opt,name=goal_id,json=goalId,proto3" json:"goal_id"`
	SubTasks            []*SubTaskPayload      `protobuf:"bytes,14,rep,name=sub_tasks,json=subTasks,proto3" json:"sub_tasks"`
	NotificationIds     []string               `protobuf:"bytes,15,rep,name=notification_ids,json=notificationIds,proto3" json:"notification_ids"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpsertWorkRequest) Reset() {
	*x = UpsertWorkRequest{}
	mi := &file_personal_schedule_service_work_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertWorkRequest) ProtoMessage() {}

func (x *UpsertWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_work_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertWorkRequest.ProtoReflect.Descriptor instead.
func (*UpsertWorkRequest) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_work_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertWorkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertWorkRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *UpsertWorkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertWorkRequest) GetShortDescriptions() string {
	if x != nil && x.ShortDescriptions != nil {
		return *x.ShortDescriptions
	}
	return ""
}

func (x *UpsertWorkRequest) GetDetailedDescription() string {
	if x != nil && x.DetailedDescription != nil {
		return *x.DetailedDescription
	}
	return ""
}

func (x *UpsertWorkRequest) GetStartDate() int64 {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return 0
}

func (x *UpsertWorkRequest) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *UpsertWorkRequest) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

func (x *UpsertWorkRequest) GetDifficultyId() string {
	if x != nil {
		return x.DifficultyId
	}
	return ""
}

func (x *UpsertWorkRequest) GetPriorityId() string {
	if x != nil {
		return x.PriorityId
	}
	return ""
}

func (x *UpsertWorkRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *UpsertWorkRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *UpsertWorkRequest) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

func (x *UpsertWorkRequest) GetSubTasks() []*SubTaskPayload {
	if x != nil {
		return x.SubTasks
	}
	return nil
}

func (x *UpsertWorkRequest) GetNotificationIds() []string {
	if x != nil {
		return x.NotificationIds
	}
	return nil
}

type UpsertWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Error         *common.Error          `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertWorkResponse) Reset() {
	*x = UpsertWorkResponse{}
	mi := &file_personal_schedule_service_work_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertWorkResponse) ProtoMessage() {}

func (x *UpsertWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_personal_schedule_service_work_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertWorkResponse.ProtoReflect.Descriptor instead.
func (*UpsertWorkResponse) Descriptor() ([]byte, []int) {
	return file_personal_schedule_service_work_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertWorkResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *UpsertWorkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpsertWorkResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_personal_schedule_service_work_proto protoreflect.FileDescriptor

const file_personal_schedule_service_work_proto_rawDesc = "" +
	"\n" +
	"$personal_schedule_service/work.proto\x12\x11personal_schedule\x1a/personal_schedule_service/common.schedule.proto\x1a\x12common/error.proto\x1a\x13common/common.proto\"\xe7\x04\n" +
	"\x11UpsertWorkRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x122\n" +
	"\x12short_descriptions\x18\x04 \x01(\tH\x01R\x11shortDescriptions\x88\x01\x01\x126\n" +
	"\x14detailed_description\x18\x05 \x01(\tH\x02R\x13detailedDescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_date\x18\x06 \x01(\x03H\x03R\tstartDate\x88\x01\x01\x12\x19\n" +
	"\bend_date\x18\a \x01(\x03R\aendDate\x12\x1b\n" +
	"\tstatus_id\x18\b \x01(\tR\bstatusId\x12#\n" +
	"\rdifficulty_id\x18\t \x01(\tR\fdifficultyId\x12\x1f\n" +
	"\vpriority_id\x18\n" +
	" \x01(\tR\n" +
	"priorityId\x12\x17\n" +
	"\atype_id\x18\v \x01(\tR\x06typeId\x12\x1f\n" +
	"\vcategory_id\x18\f \x01(\tR\n" +
	"categoryId\x12\x17\n" +
	"\agoal_id\x18\r \x01(\tR\x06goalId\x12>\n" +
	"\tsub_tasks\x18\x0e \x03(\v2!.personal_schedule.SubTaskPayloadR\bsubTasks\x12)\n" +
	"\x10notification_ids\x18\x0f \x03(\tR\x0fnotificationIdsB\x05\n" +
	"\x03_idB\x15\n" +
	"\x13_short_descriptionsB\x17\n" +
	"\x15_detailed_descriptionB\r\n" +
	"\v_start_date\"\x81\x01\n" +
	"\x12UpsertWorkResponse\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x05error\x18\x04 \x01(\v2\r.common.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2h\n" +
	"\vWorkService\x12Y\n" +
	"\n" +
	"UpsertWork\x12$.personal_schedule.UpsertWorkRequest\x1a%.personal_schedule.UpsertWorkResponseB\x19Z\x17proto/personal_scheduleb\x06proto3"

var (
	file_personal_schedule_service_work_proto_rawDescOnce sync.Once
	file_personal_schedule_service_work_proto_rawDescData []byte
)

func file_personal_schedule_service_work_proto_rawDescGZIP() []byte {
	file_personal_schedule_service_work_proto_rawDescOnce.Do(func() {
		file_personal_schedule_service_work_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_personal_schedule_service_work_proto_rawDesc), len(file_personal_schedule_service_work_proto_rawDesc)))
	})
	return file_personal_schedule_service_work_proto_rawDescData
}

var file_personal_schedule_service_work_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_personal_schedule_service_work_proto_goTypes = []any{
	(*UpsertWorkRequest)(nil),  // 0: personal_schedule.UpsertWorkRequest
	(*UpsertWorkResponse)(nil), // 1: personal_schedule.UpsertWorkResponse
	(*SubTaskPayload)(nil),     // 2: personal_schedule.SubTaskPayload
	(*common.Error)(nil),       // 3: common.Error
}
var file_personal_schedule_service_work_proto_depIdxs = []int32{
	2, // 0: personal_schedule.UpsertWorkRequest.sub_tasks:type_name -> personal_schedule.SubTaskPayload
	3, // 1: personal_schedule.UpsertWorkResponse.error:type_name -> common.Error
	0, // 2: personal_schedule.WorkService.UpsertWork:input_type -> personal_schedule.UpsertWorkRequest
	1, // 3: personal_schedule.WorkService.UpsertWork:output_type -> personal_schedule.UpsertWorkResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_personal_schedule_service_work_proto_init() }
func file_personal_schedule_service_work_proto_init() {
	if File_personal_schedule_service_work_proto != nil {
		return
	}
	file_personal_schedule_service_common_schedule_proto_init()
	file_personal_schedule_service_work_proto_msgTypes[0].OneofWrappers = []any{}
	file_personal_schedule_service_work_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_personal_schedule_service_work_proto_rawDesc), len(file_personal_schedule_service_work_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_personal_schedule_service_work_proto_goTypes,
		DependencyIndexes: file_personal_schedule_service_work_proto_depIdxs,
		MessageInfos:      file_personal_schedule_service_work_proto_msgTypes,
	}.Build()
	File_personal_schedule_service_work_proto = out.File
	file_personal_schedule_service_work_proto_goTypes = nil
	file_personal_schedule_service_work_proto_depIdxs = nil
}
