// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: notification_service/user.notification.proto

package notification_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "schedule_gateway/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserNotificationService_UpsertUserFCMToken_FullMethodName = "/notification.UserNotificationService/UpsertUserFCMToken"
)

// UserNotificationServiceClient is the client API for UserNotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserNotificationServiceClient interface {
	UpsertUserFCMToken(ctx context.Context, in *UpsertUserFCMTokenRequest, opts ...grpc.CallOption) (*common.EmptyResponse, error)
}

type userNotificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserNotificationServiceClient(cc grpc.ClientConnInterface) UserNotificationServiceClient {
	return &userNotificationServiceClient{cc}
}

func (c *userNotificationServiceClient) UpsertUserFCMToken(ctx context.Context, in *UpsertUserFCMTokenRequest, opts ...grpc.CallOption) (*common.EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.EmptyResponse)
	err := c.cc.Invoke(ctx, UserNotificationService_UpsertUserFCMToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserNotificationServiceServer is the server API for UserNotificationService service.
// All implementations must embed UnimplementedUserNotificationServiceServer
// for forward compatibility.
type UserNotificationServiceServer interface {
	UpsertUserFCMToken(context.Context, *UpsertUserFCMTokenRequest) (*common.EmptyResponse, error)
	mustEmbedUnimplementedUserNotificationServiceServer()
}

// UnimplementedUserNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserNotificationServiceServer struct{}

func (UnimplementedUserNotificationServiceServer) UpsertUserFCMToken(context.Context, *UpsertUserFCMTokenRequest) (*common.EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertUserFCMToken not implemented")
}
func (UnimplementedUserNotificationServiceServer) mustEmbedUnimplementedUserNotificationServiceServer() {
}
func (UnimplementedUserNotificationServiceServer) testEmbeddedByValue() {}

// UnsafeUserNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserNotificationServiceServer will
// result in compilation errors.
type UnsafeUserNotificationServiceServer interface {
	mustEmbedUnimplementedUserNotificationServiceServer()
}

func RegisterUserNotificationServiceServer(s grpc.ServiceRegistrar, srv UserNotificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserNotificationService_ServiceDesc, srv)
}

func _UserNotificationService_UpsertUserFCMToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertUserFCMTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserNotificationServiceServer).UpsertUserFCMToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserNotificationService_UpsertUserFCMToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserNotificationServiceServer).UpsertUserFCMToken(ctx, req.(*UpsertUserFCMTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserNotificationService_ServiceDesc is the grpc.ServiceDesc for UserNotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserNotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.UserNotificationService",
	HandlerType: (*UserNotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertUserFCMToken",
			Handler:    _UserNotificationService_UpsertUserFCMToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification_service/user.notification.proto",
}
