// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: auth_service/permission.v1.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionsRequest) Reset() {
	*x = GetPermissionsRequest{}
	mi := &file_auth_service_permission_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsRequest) ProtoMessage() {}

func (x *GetPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_v1_proto_rawDescGZIP(), []int{0}
}

func (x *GetPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionsResponse) Reset() {
	*x = GetPermissionsResponse{}
	mi := &file_auth_service_permission_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsResponse) ProtoMessage() {}

func (x *GetPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_v1_proto_rawDescGZIP(), []int{1}
}

func (x *GetPermissionsResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_auth_service_permission_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_v1_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionId  string                 `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponse) Reset() {
	*x = CreatePermissionResponse{}
	mi := &file_auth_service_permission_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponse) ProtoMessage() {}

func (x *CreatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_v1_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePermissionResponse) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

type UpdatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionId  string                 `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionRequest) Reset() {
	*x = UpdatePermissionRequest{}
	mi := &file_auth_service_permission_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionRequest) ProtoMessage() {}

func (x *UpdatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_v1_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *UpdatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionResponse) Reset() {
	*x = UpdatePermissionResponse{}
	mi := &file_auth_service_permission_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionResponse) ProtoMessage() {}

func (x *UpdatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_v1_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePermissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeletePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionId  string                 `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_auth_service_permission_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_v1_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

type DeletePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionResponse) Reset() {
	*x = DeletePermissionResponse{}
	mi := &file_auth_service_permission_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionResponse) ProtoMessage() {}

func (x *DeletePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionResponse.ProtoReflect.Descriptor instead.
func (*DeletePermissionResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_v1_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePermissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AssignPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionId  string                 `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionRequest) Reset() {
	*x = AssignPermissionRequest{}
	mi := &file_auth_service_permission_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionRequest) ProtoMessage() {}

func (x *AssignPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionRequest.ProtoReflect.Descriptor instead.
func (*AssignPermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_v1_proto_rawDescGZIP(), []int{8}
}

func (x *AssignPermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *AssignPermissionRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type AssignPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionResponse) Reset() {
	*x = AssignPermissionResponse{}
	mi := &file_auth_service_permission_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionResponse) ProtoMessage() {}

func (x *AssignPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_permission_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionResponse.ProtoReflect.Descriptor instead.
func (*AssignPermissionResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_permission_v1_proto_rawDescGZIP(), []int{9}
}

func (x *AssignPermissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_auth_service_permission_v1_proto protoreflect.FileDescriptor

const file_auth_service_permission_v1_proto_rawDesc = "" +
	"\n" +
	" auth_service/permission.v1.proto\x12\x04grpc\"0\n" +
	"\x15GetPermissionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\":\n" +
	"\x16GetPermissionsResponse\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions\"O\n" +
	"\x17CreatePermissionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"?\n" +
	"\x18CreatePermissionResponse\x12#\n" +
	"\rpermission_id\x18\x01 \x01(\tR\fpermissionId\"t\n" +
	"\x17UpdatePermissionRequest\x12#\n" +
	"\rpermission_id\x18\x01 \x01(\tR\fpermissionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"4\n" +
	"\x18UpdatePermissionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\">\n" +
	"\x17DeletePermissionRequest\x12#\n" +
	"\rpermission_id\x18\x01 \x01(\tR\fpermissionId\"4\n" +
	"\x18DeletePermissionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"W\n" +
	"\x17AssignPermissionRequest\x12#\n" +
	"\rpermission_id\x18\x01 \x01(\tR\fpermissionId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\"4\n" +
	"\x18AssignPermissionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb2\x03\n" +
	"\x11PermissionService\x12K\n" +
	"\x0eGetPermissions\x12\x1b.grpc.GetPermissionsRequest\x1a\x1c.grpc.GetPermissionsResponse\x12Q\n" +
	"\x10CreatePermission\x12\x1d.grpc.CreatePermissionRequest\x1a\x1e.grpc.CreatePermissionResponse\x12Q\n" +
	"\x10UpdatePermission\x12\x1d.grpc.UpdatePermissionRequest\x1a\x1e.grpc.UpdatePermissionResponse\x12Q\n" +
	"\x10DeletePermission\x12\x1d.grpc.DeletePermissionRequest\x1a\x1e.grpc.DeletePermissionResponse\x12W\n" +
	"\x16AssignPermissionToRole\x12\x1d.grpc.AssignPermissionRequest\x1a\x1e.grpc.AssignPermissionResponseB Z\x1einternal/grpc/permission.v1;v1b\x06proto3"

var (
	file_auth_service_permission_v1_proto_rawDescOnce sync.Once
	file_auth_service_permission_v1_proto_rawDescData []byte
)

func file_auth_service_permission_v1_proto_rawDescGZIP() []byte {
	file_auth_service_permission_v1_proto_rawDescOnce.Do(func() {
		file_auth_service_permission_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_service_permission_v1_proto_rawDesc), len(file_auth_service_permission_v1_proto_rawDesc)))
	})
	return file_auth_service_permission_v1_proto_rawDescData
}

var file_auth_service_permission_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_auth_service_permission_v1_proto_goTypes = []any{
	(*GetPermissionsRequest)(nil),    // 0: grpc.GetPermissionsRequest
	(*GetPermissionsResponse)(nil),   // 1: grpc.GetPermissionsResponse
	(*CreatePermissionRequest)(nil),  // 2: grpc.CreatePermissionRequest
	(*CreatePermissionResponse)(nil), // 3: grpc.CreatePermissionResponse
	(*UpdatePermissionRequest)(nil),  // 4: grpc.UpdatePermissionRequest
	(*UpdatePermissionResponse)(nil), // 5: grpc.UpdatePermissionResponse
	(*DeletePermissionRequest)(nil),  // 6: grpc.DeletePermissionRequest
	(*DeletePermissionResponse)(nil), // 7: grpc.DeletePermissionResponse
	(*AssignPermissionRequest)(nil),  // 8: grpc.AssignPermissionRequest
	(*AssignPermissionResponse)(nil), // 9: grpc.AssignPermissionResponse
}
var file_auth_service_permission_v1_proto_depIdxs = []int32{
	0, // 0: grpc.PermissionService.GetPermissions:input_type -> grpc.GetPermissionsRequest
	2, // 1: grpc.PermissionService.CreatePermission:input_type -> grpc.CreatePermissionRequest
	4, // 2: grpc.PermissionService.UpdatePermission:input_type -> grpc.UpdatePermissionRequest
	6, // 3: grpc.PermissionService.DeletePermission:input_type -> grpc.DeletePermissionRequest
	8, // 4: grpc.PermissionService.AssignPermissionToRole:input_type -> grpc.AssignPermissionRequest
	1, // 5: grpc.PermissionService.GetPermissions:output_type -> grpc.GetPermissionsResponse
	3, // 6: grpc.PermissionService.CreatePermission:output_type -> grpc.CreatePermissionResponse
	5, // 7: grpc.PermissionService.UpdatePermission:output_type -> grpc.UpdatePermissionResponse
	7, // 8: grpc.PermissionService.DeletePermission:output_type -> grpc.DeletePermissionResponse
	9, // 9: grpc.PermissionService.AssignPermissionToRole:output_type -> grpc.AssignPermissionResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_service_permission_v1_proto_init() }
func file_auth_service_permission_v1_proto_init() {
	if File_auth_service_permission_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_service_permission_v1_proto_rawDesc), len(file_auth_service_permission_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_service_permission_v1_proto_goTypes,
		DependencyIndexes: file_auth_service_permission_v1_proto_depIdxs,
		MessageInfos:      file_auth_service_permission_v1_proto_msgTypes,
	}.Build()
	File_auth_service_permission_v1_proto = out.File
	file_auth_service_permission_v1_proto_goTypes = nil
	file_auth_service_permission_v1_proto_depIdxs = nil
}
